version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: apm-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: apmtest
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - apm-network

  oracle:
    image: gvenzl/oracle-xe:latest
    container_name: apm-oracle
    environment:
      ORACLE_PASSWORD: oracle
    ports:
      - "1521:1521"
    volumes:
      - oracle-data:/opt/oracle/oradata
    networks:
      - apm-network

networks:
  apm-network:
    driver: bridge

volumes:
  mysql-data:
  oracle-data: 