version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: apm-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: apmtest
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - apm-network

  oracle:
    image: gvenzl/oracle-xe:latest
    container_name: apm-oracle
    environment:
      ORACLE_PASSWORD: oracle
    ports:
      - "1521:1521"
    volumes:
      - oracle-data:/opt/oracle/oradata
    networks:
      - apm-network

  # Sentry 서비스들
  redis:
    image: redis:6.2-alpine
    container_name: apm-redis
    networks:
      - apm-network

  postgres:
    image: postgres:14
    container_name: apm-postgres
    environment:
      POSTGRES_USER: sentry
      POSTGRES_PASSWORD: sentry
      POSTGRES_DB: sentry
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - apm-network

  clickhouse:
    image: clickhouse/clickhouse-server:22.3
    container_name: apm-clickhouse
    volumes:
      - clickhouse-data:/var/lib/clickhouse
    networks:
      - apm-network

  sentry:
    image: getsentry/sentry:nightly
    container_name: apm-sentry
    depends_on:
      - redis
      - postgres
      - clickhouse
    environment:
      SENTRY_SECRET_KEY: 'your-secret-key-here'
      SENTRY_POSTGRES_HOST: postgres
      SENTRY_DB_USER: sentry
      SENTRY_DB_PASSWORD: sentry
      SENTRY_REDIS_HOST: redis
      SENTRY_CLICKHOUSE_HOST: clickhouse
    ports:
      - "9000:9000"
    networks:
      - apm-network

  app:
    build: .
    container_name: apm-app
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=default
      - SPRING_DATASOURCE_MYSQL_URL=jdbc:mysql://mysql:3306/apmtest
      - SPRING_DATASOURCE_MYSQL_USERNAME=user
      - SPRING_DATASOURCE_MYSQL_PASSWORD=password
      - SPRING_DATASOURCE_ORACLE_URL=jdbc:oracle:thin:@oracle:1521/XEPDB1
      - SPRING_DATASOURCE_ORACLE_USERNAME=system
      - SPRING_DATASOURCE_ORACLE_PASSWORD=oracle
      - SENTRY_DSN=http://sentry:9000
    depends_on:
      - mysql
      - oracle
      - sentry
    networks:
      - apm-network

networks:
  apm-network:
    driver: bridge

volumes:
  mysql-data:
  oracle-data:
  postgres-data:
  clickhouse-data: 