server:
  port: 8080

spring:
  application:
    name: apm-test

# MySQL 설정
mysql:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    jdbc-url: jdbc:mysql://localhost:3306/apmtest?useSSL=false&allowPublicKeyRetrieval=true
    username: user
    password: password
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true

# Oracle 설정
oracle:
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    jdbc-url: jdbc:oracle:thin:@localhost:1521/XEPDB1
    username: system
    password: oracle
  jpa:
    database-platform: org.hibernate.dialect.OracleDialect
    hibernate:
      ddl-auto: update
    show-sql: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

sentry:
  dsn: http://81e8ea40ce8a7591b6bd7beb7c359ee2@localhost:9000/2
  environment: development
  sample-rate: 1.0
  debug: true
  traces-sample-rate: 1.0
  send-default-pii: true
